-- Se ejecuta al iniciar el contenedor de Postgres
\connect loan_applications;

-- === tablas catálogo ===
CREATE TABLE IF NOT EXISTS loan_type (
  id_loan_type        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                VARCHAR(100) NOT NULL UNIQUE,
  min_amount          NUMERIC(12,2) NOT NULL,
  max_amount          NUMERIC(12,2) NOT NULL,
  interest_rate       NUMERIC(5,2)  NOT NULL,
  automatic_validation BOOLEAN      NOT NULL DEFAULT FALSE,
  CONSTRAINT ck_amount_range CHECK (min_amount > 0 AND max_amount >= min_amount),
  CONSTRAINT ck_interest_range CHECK (interest_rate >= 0 AND interest_rate <= 100)
);

CREATE TABLE IF NOT EXISTS states (
  id_state     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(100) NOT NULL UNIQUE,
  description  VARCHAR(255)
);

-- === tabla principal de solicitudes ===
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS application (
  id_application        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  amount                NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  term_months           INTEGER NOT NULL CHECK (term_months BETWEEN 1 AND 360),
  email                 VARCHAR(255) NOT NULL,
  identification_number VARCHAR(50)  NOT NULL,
  id_state              INTEGER NOT NULL REFERENCES states(id_state),
  id_loan_type          INTEGER NOT NULL REFERENCES loan_type(id_loan_type),
  created_at            TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMP NOT NULL DEFAULT NOW()
);

-- índices útiles
CREATE INDEX IF NOT EXISTS idx_application_email
  ON application (email);

CREATE INDEX IF NOT EXISTS idx_application_identification
  ON application (identification_number);

CREATE INDEX IF NOT EXISTS idx_application_state
  ON application (id_state);
